#!/bin/bash

### VARIABLES

### APK REPOSITORIES
echo -e "### CONTROLLED BY PDC\n\n#/media/sdb1/apks\nhttp://dl-cdn.alpinelinux.org/alpine/v3.19/main\nhttp://dl-cdn.alpinelinux.org/alpine/v3.19/community\n" > /etc/apk/repositories

### NFS MODULE
if [[ $(yq eval '.system.nfs.enabled // false' /root/.config/alpine-linux-pdc/config.yaml) == true ]]; then
  if [[ -z "$(which nfsstat)" ]]; then
    ### INSTALL NFS-UTILS
    apk add -U nfs-utils --quiet

    ### ENABLE BOOT START
    rc-update add nfsmount

    ### START SERVICE
    rc-service nfsmount start
  else
    echo -e "NFS-UTILS IS ALREADY INSTALLED, SKIPPING..."
  fi

  if [[ $(yq eval '.system.nfs.mounts.media // false' /root/.config/alpine-linux-pdc/config.yaml) == true ]]; then
    ### CREATE BINDING DIRECTORY
    mkdir -p /mnt/media

    if [[ -z "$(grep -qs '/mnt/media ' /proc/mounts)" ]]; then
      if [[ -z "$(grep -qs '/mnt/media' /etc/fstab)" ]]; then
        ### CREATE NFS MOUNT ENTRY IN FSTAB
        echo -e "$(yq eval '.system.nfs.address // \"\"' /root/.config/alpine-linux-pdc/config.yaml):/volume1/media /mnt/media nfs rw,vers=4,rsize=32768,wsize=32768,soft 0 0" >> /etc/fstab

        ### MOUNT
        mount -a
      else
        ### MOUNT
        mount -a
      fi
    else
      echo -e "MEDIA MOUNT EXISTS, SKIPPING..."
    fi
  else
    echo -e "SYSTEM.NFS.MOUNTS.MEDIA IS FALSE, SKIPPING..."
  fi
else
  echo -e "SYSTEM.NFS.ENABLED IS FALSE, SKIPPING..."
fi

### DOCKER MODULE
if [[ $(yq eval '.docker.enabled // false' /root/.config/alpine-linux-pdc/config.yaml) == true ]]; then
  if [[ -z "$(which docker)" ]]; then
    ### INSTALL DOCKER
    apk add -U docker --quiet

    ### ENABLE BOOT START
    rc-update add docker boot

    ### START SERVICE
    rc-service docker start
  else
    echo -e "DOCKER IS ALREADY INSTALLED, SKIPPING..."
  fi

  if [[ $(yq eval '.docker.containers.portainer // false' /root/.config/alpine-linux-pdc/config.yaml) == true ]]; then
    if [[ -z "$(docker container list --filter 'name=portainer' --quiet)" ]]; then
      if [[ -z "$(docker volume list --filter 'name=portainer_data' --quiet)" ]]; then
        ### CREATE PORTAINER_DATA VOLUME
        docker volume create portainer_data
      else
        echo -e "PORTAINER_DATA VOLUME EXISTS, SKIPPING..."
      fi

      ### CREATE PORTAINER CONTAINER
      docker run -d -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data -l com.centurylinklabs.watchtower.enable=true portainer/portainer-ce:latest
    else
      echo -e "PORTAINER CONTAINER EXISTS, SKIPPING..."
    fi
  else
    echo -e "DOCKER.CONTAINERS.PORTAINER IS FALSE, SKIPPING"
  fi
else
  echo -e "DOCKER.ENABLED IS FALSE, SKIPPING..."
fi

### NEOFETCH MODULE

### UFW MODULE
