#!/bin/bash

### VARIABLES
REPOSITORY_URL=https://raw.githubusercontent.com/chadwagoner/alpine-linux-pdc/main
HEADER_NO_CACHE="Cache-Control: no-cache, no-store"

### UPDATE PDC TO CRON (/etc/periodic/hourly)
echo -e "UPDATING PDC"
curl -L -o /etc/periodic/hourly/pdc -H '$HEADER_NO_CACHE' $REPOSITORY_URL/pdc --silent
echo -e ""

### SET PDC OWNERSHIP
if [[ "$(stat -c '%U:%G' /etc/periodic/hourly/pdc)" != "root:root" ]]; then
  echo -e "PDC OWNERSHIP IS WRONG, CHANGING..."
  chown root:root /etc/periodic/hourly/pdc
  echo -e ""
else
  echo -e "PDC OWNERSHIP IS CORRECT, SKIPPING..."
  echo -e ""
fi

### SET PDC PERMISSIONS
if [[ "$(stat -c '%a' /etc/periodic/hourly/pdc)" != 700 ]]; then
  echo -e "PDC PERMISSIONS ARE WRONG, CHANGING..."
  chmod 700 /etc/periodic/hourly/pdc
  echo -e ""
else
  echo -e "PDC PERMISSIONS ARE CORRECT, SKIPPING..."
  echo -e ""
fi