services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: docker
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/.config/services/plex/data:/config
      - /mnt/media:/media
    restart: unless-stopped