services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      TRAEFIK_API: true
      TRAEFIK_API_DASHBOARD: true
      TRAEFIK_API_DEBUG: true
      TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_TAILSCALE: TRUE
      TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: ":80"
      TRAEFIK_ENTRYPOINTS_HTTP_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: "https"
      TRAEFIK_ENTRYPOINTS_HTTP_HTTP_REDIRECTIONS_ENTRYPOINT_TO: "https"
      TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: ":443"
      TRAEFIK_PROVIDERS_DOCKER: true
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: false
      TRAEFIK_PROVIDERS_FILE_FILENAME: "/config.yml"
      TRAEFIK_SERVERSTRANSPORT_INSECURESKIPVERIFY: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/.config/services/traefik/config.yml:/config.yml:ro
    labels:
      traefik.enable: true
      traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto: "https"
      traefik.http.middlewares.traefik-auth.basicauth.users: "${ADMIN_CREDS}"
      traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.traefik.entrypoints: "http"
      traefik.http.routers.traefik.middlewares: "traefik-https-redirect"
      traefik.http.routers.traefik.rule: "Host(`${TAILSCALE_MACHINE}.${TAILSCALE_TAILNET}`) && Path(`/traefik`)"
      traefik.http.routers.traefik.tls.certresolver: myresolver

networks:
  proxy:
    external: true