#!/bin/bash

### GLOBAL VARIABLES
REPOSITORY_URL=https://raw.githubusercontent.com/chadwagoner/alpine-linux-pdc/main
HEADER_NO_CACHE="Cache-Control: no-cache, no-store"

### GLOBAL FUNCTIONS
create_directory () {
  mkdir -p $1
}

create_file () {
  touch $1
}

set_ownership () {
  chown $2:$2 $1
}

set_permission () {
  chmod $2 $1
}

### UPDATE PDC
LOCAL_PDC=$(cat /etc/periodic/hourly/pdc | sha256sum | awk '{print $1}')
REMOTE_PDC=$(curl -sL -H '$HEADER_NO_CACHE' $REPOSITORY_URL/scripts/pdc | sha256sum | awk '{print $1}')

if [[ $LOCAL_PDC != $REMOTE_PDC ]]; then
  echo -e "PDC MISMATCH, UPDATING..."
  curl -sL -o /etc/periodic/hourly/pdc -H '$HEADER_NO_CACHE' $REPOSITORY_URL/scripts/pdc
  echo -e ""

  ### SET PDC OWNERSHIP
  if [[ "$(stat -c '%U:%G' /etc/periodic/hourly/pdc)" != "root:root" ]]; then
    echo -e "PDC OWNERSHIP IS WRONG, CHANGING..."
    set_ownership /etc/periodic/hourly/pdc root
    echo -e ""
  else
    echo -e "PDC OWNERSHIP IS CORRECT, SKIPPING..."
    echo -e ""
  fi

  ### SET PDC PERMISSIONS
  if [[ "$(stat -c '%a' /etc/periodic/hourly/pdc)" != 700 ]]; then
    echo -e "PDC PERMISSIONS ARE WRONG, CHANGING..."
    set_permission /etc/periodic/hourly/pdc 700
    echo -e ""
  else
    echo -e "PDC PERMISSIONS ARE CORRECT, SKIPPING..."
    echo -e ""
  fi
else
  echo -e "PDC LATEST, SKIPPING..."
  echo -e ""
fi
